# Generated by Django 2.2.6 on 2019-11-21 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Name', models.CharField(max_length=250)),
                ('rutADM', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('emailadm', models.EmailField(max_length=250, verbose_name='User Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('fotoRece', models.ImageField(upload_to=None)),
                ('ingrediente', models.TextField(max_length=500)),
                ('pasos', models.TextField(max_length=500)),
                ('id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('admimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='RecePremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/', verbose_name='')),
                ('ingre', models.TextField(max_length=500)),
                ('pasosvidio', models.TextField(max_length=500)),
                ('idvidio', models.TextField(max_length=12)),
                ('admvid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, verbose_name='User Mail')),
                ('useradm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.Administrador')),
            ],
        ),
    ]
